<?php
/*********************************************************************
 * Extension configuration file for ext "gb_events".
 *
 * Generated by ext 30-09-2013 06:02 UTC
 *
 * https://github.com/t3elmar/Ext
 *********************************************************************/
$EM_CONF[$_EXTKEY] = array(
  'title' => 'Event calendar',
  'description' => 'A simple calendar for upcoming events.',
  'category' => 'plugin',
  'author' => 'Morton Jonuschat',
  'author_email' => 'm.jonuschat@gute-botschafter.de',
  'author_company' => 'Gute Botschafter GmbH',
  'shy' => '',
  'dependencies' => 'cms,extbase,fluid',
  'conflicts' => '',
  'priority' => '',
  'module' => '',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => '1',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '1.3.4',
  'constraints' => array(
    'depends' => array(
      'cms' => '',
      'extbase' => '6.0',
      'fluid' => '6.0',
      'typo3' => '6.0.0-6.1.99',
    ) ,
    'conflicts' => array() ,
    'suggests' => array() ,
  ) ,
  'comment' => 'Bugfixes for KeSearch and record creation',
  'user' => 'gutebotschafter',
);
